# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff223b56d9b5532a86fc7196b0ddf3dbecdc3c17b5b2ed069a326cef803e9c8cfee053f9e49f362b06d8d82e6154633a0600a0c128cc693cb6bd1d720ea12ce1

test:
  secret_key_base: f53c779d54f640fd6dbe7deb84182cf7d6830c3bcb7b0d3011788ab9b54c33e5636b425abc5cb9961733ab79c9e4efbe6c8a1413c0fac1d5bf5867c1e861bc88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
